[package]
name = "indicator"
version = "0.1.9"
edition = "2021"
authors = ["Nouzan"]
license = "MIT"
description = "Abstractions for stream aggregation, we call them `Indicator` s."
repository = "https://github.com/Nouzan/indicator"
keywords = ["stream", "no_std", "stream-processing", "aggregation"]

[dependencies.arrayvec]
version = "0.7"
optional = true
default-features = false

[dependencies.time]
version = "0.3"
default-features = false

[dependencies.futures]
version = "0.3"
optional = true
default-features = false

[dependencies.pin-project-lite]
version = "0.2.7"
optional = true

[dev-dependencies]
time = { version = "0.3", default-features = false, features = ["macros"] }
rust_decimal = "1.17.0"
rust_decimal_macros = "1.17.0"
arrayvec = "0.7"

[features]
default = ["std", "stream", "array-vec"]
std = ["time/std", "futures/std"]
array-vec = ["arrayvec"]
stream = ["futures", "pin-project-lite"]
